name: Refresh data
on:
  push:
    branches:
      - '*'

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: satak/webrequest-action@master
        with:
          url: https://my-json-server.typicode.com/typicode/demo/posts
          method: GET

      - run: |
        $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
        Write-Host "Time from output $($output.time) statusCode $($output.statusCode) data $($output.data)"
